export enum UserRole {
  STUDENT = "STUDENT",
  LECTURER = "LECTURER",
  ADMIN = "ADMIN",
}
export enum FacilityType {
  CLASSROOM = "CLASSROOM",
  HALL = "HALL",
  LAB = "LAB",
}
export enum BookingType {
  ACADEMIC = "ACADEMIC",
  EVENT = "EVENT",
  PERSONAL = "PERSONAL",
}
export enum BookingStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  WAITING_PAYMENT = "WAITING_PAYMENT",
  PENDING_RESCHEDULE = "PENDING_RESCHEDULE",
  CONFIRMED = "CONFIRMED",
  IN_USE = "IN_USE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  REJECTED = "REJECTED",
  RESCHEDULED = "RESCHEDULED",
  ADMIN_HOLD = "ADMIN_HOLD",
  REVIEW_REQUIRED = "REVIEW_REQUIRED",
}
export enum EquipmentStatus {
  GOOD = "GOOD",
  BROKEN = "BROKEN",
  MAINTENANCE = "MAINTENANCE",
}
export enum PriceType {
  PER_HOUR = "PER_HOUR",
  PER_BOOKING = "PER_BOOKING",
  ONE_TIME = "ONE_TIME",
}
export enum TransactionType {
  DEPOSIT = "DEPOSIT",
  RENTAL_FEE = "RENTAL_FEE",
  FINE = "FINE",
}
