export enum UserRole { STUDENT = 'STUDENT', LECTURER = 'LECTURER', ADMIN = 'ADMIN' }
export enum FacilityType { CLASSROOM = 'CLASSROOM', HALL = 'HALL', LAB = 'LAB' }
export enum BookingType { ACADEMIC = 'ACADEMIC', EVENT = 'EVENT', PERSONAL = 'PERSONAL' }
export enum BookingStatus { PENDING = 'PENDING', APPROVED = 'APPROVED', REJECTED = 'REJECTED', CANCELLED = 'CANCELLED', COMPLETED = 'COMPLETED', RESCHEDULED = 'RESCHEDULED' }
export enum EquipmentStatus { GOOD = 'GOOD', BROKEN = 'BROKEN', MAINTENANCE = 'MAINTENANCE' }